language: ruby
rvm:
  - 2.1.5
gemfile:
  - Gemfile
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
  sauce_connect: true
env:
  - NOSAUCE=true
  - SAUCE_BROWSER="internet explorer" SAUCE_VERSION=11
  - SAUCE_BROWSER="internet explorer" SAUCE_VERSION=10
  - SAUCE_BROWSER="internet explorer" SAUCE_VERSION=9
  - SAUCE_BROWSER="internet explorer" SAUCE_VERSION=8
  - SAUCE_BROWSER="chrome"
  - SAUCE_BROWSER="firefox"
  - SAUCE_BROWSER="safari" SAUCE_VERSION=8
  - SAUCE_BROWSER="safari" SAUCE_VERSION=7
